mainBuild:
    name: ocjs.full.js

additionalCppCode: |
    typedef Handle(IMeshTools_Context) Handle_IMeshTools_Context;
    class OCJS {
    public:
      static Standard_Failure* getStandard_FailureData(intptr_t exceptionPtr) {
        return reinterpret_cast<Standard_Failure*>(exceptionPtr);
      }
    };
